services:
- type: web
  name: sherlock-rest-nodocker
  env: python
  plan: starter
  buildCommand: pip3 install -r requirements.txt
  startCommand: cd sherlock_rest_service && gunicorn sherlock_rest_service.wsgi:application
#  autoDeploy: false
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DJANGO_SECRET_KEY
      generateValue: true
